'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { ArrowLeft, ShoppingBag, Loader2, Download, CheckCircle } from 'lucide-react';
import type { GeneratedContent, ImageFiles, AllImagePayloads, ImagePayload } from '@/app/lib/amazon-assistant/types';
import { getApiKey } from '@/app/lib/api-keys';

interface AmazonAssistantData {
  // テキストデータ
  storyContent?: string;
  researchContent?: string;
  worldReport?: string;
  // 画像データ（base64形式）
  characterImage?: string;
  memorableImages?: string[]; // 3枚の印象的な画像
  // その他
  language?: 'ja' | 'en';
}

interface AmazonAssistantInterfaceProps {
  initialData?: AmazonAssistantData;
  mode: 'semi-auto' | 'manual';
  onClose?: () => void;
}

export const AmazonAssistantInterface: React.FC<AmazonAssistantInterfaceProps> = ({
  initialData,
  mode,
  onClose,
}) => {
  const [text, setText] = useState<string>('');
  const [language, setLanguage] = useState<'ja' | 'en'>('ja');
  const [images, setImages] = useState<ImageFiles>({
    character: null,
    memorable1: null,
    memorable2: null,
    memorable3: null,
    author: null,
  });
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);

  // セミオートモード：初期データから自動生成
  useEffect(() => {
    if (mode === 'semi-auto' && initialData && !autoGenerated) {
      // テキストを結合
      let combinedText = '';
      if (initialData.researchContent) {
        combinedText += `# リサーチ内容\n${initialData.researchContent}\n\n`;
      }
      if (initialData.worldReport) {
        combinedText += `# 世界観レポート\n${initialData.worldReport}\n\n`;
      }
      if (initialData.storyContent) {
        combinedText += `# ストーリー内容\n${initialData.storyContent}\n\n`;
      }
      setText(combinedText);
      
      // 言語設定
      if (initialData.language) {
        setLanguage(initialData.language);
      }

      // 画像をFileオブジェクトに変換
      const imageFiles: ImageFiles = {
        character: null,
        memorable1: null,
        memorable2: null,
        memorable3: null,
        author: null,
      };

      if (initialData.characterImage) {
        imageFiles.character = base64ToFile(initialData.characterImage, 'character.png');
      }

      if (initialData.memorableImages && initialData.memorableImages.length >= 3) {
        imageFiles.memorable1 = base64ToFile(initialData.memorableImages[0], 'memorable1.png');
        imageFiles.memorable2 = base64ToFile(initialData.memorableImages[1], 'memorable2.png');
        imageFiles.memorable3 = base64ToFile(initialData.memorableImages[2], 'memorable2.png');
      }

      setImages(imageFiles);

      // 自動生成を実行
      if (combinedText && imageFiles.character && imageFiles.memorable1 && imageFiles.memorable2 && imageFiles.memorable3) {
        setAutoGenerated(true);
        handleGenerate(combinedText, imageFiles, initialData.language || 'ja');
      }
    }
  }, [mode, initialData, autoGenerated]);

  // base64文字列をFileオブジェクトに変換
  const base64ToFile = (base64: string, filename: string): File => {
    const arr = base64.split(',');
    const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/png';
    const bstr = atob(arr[1] || arr[0]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, { type: mime });
  };

  // Fileをbase64に変換
  const fileToBase64 = (file: File): Promise<ImagePayload> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        const [mimeType, base64Data] = result.split(';base64,');
        resolve({ mimeType: mimeType.replace('data:', ''), data: base64Data });
      };
      reader.onerror = (error) => reject(error);
    });
  };

  // 生成実行
  const handleGenerate = useCallback(async (textInput: string, imageFiles: ImageFiles, lang: string) => {
    if (!textInput || !imageFiles.character || !imageFiles.memorable1 || !imageFiles.memorable2 || !imageFiles.memorable3) {
      setError('テキストと、キャラクターおよび印象的な画像（3枚）は必須です。');
      return;
    }

    setIsLoading(true);
    setError(null);
    setGeneratedContent(null);

    try {
      const requiredImagePromises = [
        fileToBase64(imageFiles.character),
        fileToBase64(imageFiles.memorable1),
        fileToBase64(imageFiles.memorable2),
        fileToBase64(imageFiles.memorable3),
      ];
      
      const [character, memorable1, memorable2, memorable3] = await Promise.all(requiredImagePromises);

      const payloads: AllImagePayloads = {
        character,
        memorable1,
        memorable2,
        memorable3,
      };

      if (imageFiles.author) {
        payloads.author = await fileToBase64(imageFiles.author);
      }

      // API呼び出し
      // getApiKey('amazon')は内部でdefaultキーにフォールバックする
      const apiKey = getApiKey('amazon');
      if (!apiKey) {
        throw new Error('APIキーが設定されていません。マンガハブの「APIキー設定」からキーを入力してください。');
      }

      const response = await fetch('/api/amazon-assistant/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          promptText: textInput,
          images: payloads,
          language: lang,
          apiKey,
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Failed to generate content');

      setGeneratedContent(data);
    } catch (e: any) {
      console.error(e);
      setError('コンテンツの生成中にエラーが発生しました。しばらくしてからもう一度お試しください。');
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleManualGenerate = () => {
    handleGenerate(text, images, language);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white shadow-sm sticky top-0 z-10">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-slate-800 tracking-tight flex items-center gap-2">
                <ShoppingBag className="w-6 h-6" />
                アマゾン戦略アシスタント
              </h1>
              <p className="text-slate-500 mt-1 text-sm">
                {mode === 'semi-auto' ? 'セミオートモード：自動生成中...' : 'マニュアルモード：手動で入力してください'}
              </p>
            </div>
            {onClose && (
              <button
                onClick={onClose}
                className="px-4 py-2 bg-gray-200 hover:bg-gray-300 rounded-lg flex items-center gap-2"
              >
                <ArrowLeft className="w-4 h-4" />
                戻る
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {mode === 'manual' && (
          <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg border border-gray-200 mb-8">
            <form onSubmit={(e) => { e.preventDefault(); handleManualGenerate(); }} className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  ターゲット市場 / 言語
                </label>
                <select
                  value={language}
                  onChange={(e) => setLanguage(e.target.value as 'ja' | 'en')}
                  className="block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md border"
                >
                  <option value="ja">日本国内向け (日本語)</option>
                  <option value="en">英語圏向け (英語 + 日本語訳)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  書籍情報（ストーリー、リサーチ、世界観レポートなど）
                </label>
                <textarea
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  rows={10}
                  className="w-full p-3 border border-gray-300 rounded-md focus:ring-indigo-500 focus:border-indigo-500"
                  placeholder="ストーリーの内容、リサーチ内容、世界観レポートなどを入力してください..."
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">キャラクター画像（必須）</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setImages(prev => ({ ...prev, character: e.target.files?.[0] || null }))}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">印象的な画像1（必須）</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setImages(prev => ({ ...prev, memorable1: e.target.files?.[0] || null }))}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">印象的な画像2（必須）</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setImages(prev => ({ ...prev, memorable2: e.target.files?.[0] || null }))}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">印象的な画像3（必須）</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setImages(prev => ({ ...prev, memorable3: e.target.files?.[0] || null }))}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">著者プロフィール画像（任意）</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setImages(prev => ({ ...prev, author: e.target.files?.[0] || null }))}
                    className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={isLoading || !text || !images.character || !images.memorable1 || !images.memorable2 || !images.memorable3}
                className="w-full bg-indigo-600 text-white font-bold py-3 px-6 rounded-lg shadow-md hover:bg-indigo-700 disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    生成中...
                  </>
                ) : (
                  <>
                    <ShoppingBag className="w-5 h-5" />
                    生成開始
                  </>
                )}
              </button>
            </form>
          </div>
        )}

        {error && (
          <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-md mb-8" role="alert">
            <p className="font-bold">エラー</p>
            <p>{error}</p>
          </div>
        )}

        {isLoading && (
          <div className="bg-white p-8 rounded-2xl shadow-lg border border-gray-200 text-center">
            <Loader2 className="w-12 h-12 animate-spin text-indigo-600 mx-auto mb-4" />
            <p className="text-lg text-slate-600">コンテンツを生成しています...</p>
            <p className="text-sm text-slate-500 mt-2">数分かかることがあります。</p>
          </div>
        )}

        {generatedContent && !isLoading && (
          <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg border border-gray-200">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                <CheckCircle className="w-6 h-6 text-green-500" />
                生成完了
              </h2>
              <button
                onClick={() => {
                  const json = JSON.stringify(generatedContent, null, 2);
                  const blob = new Blob([json], { type: 'application/json' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = 'amazon-assistant-output.json';
                  a.click();
                }}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                JSONダウンロード
              </button>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-bold text-slate-700 mb-2">キーワード（7つ）</h3>
                <div className="flex flex-wrap gap-2">
                  {generatedContent.kdpDetails.keywords.map((keyword, index) => (
                    <span key={index} className="px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-sm">
                      {keyword}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-slate-700 mb-2">カテゴリー（3つ）</h3>
                <div className="flex flex-wrap gap-2">
                  {generatedContent.kdpDetails.categories.map((category, index) => (
                    <span key={index} className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm">
                      {category}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-slate-700 mb-2">紹介文</h3>
                <div className="p-4 bg-gray-50 rounded-lg whitespace-pre-wrap text-sm">
                  {generatedContent.kdpDetails.description}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-slate-700 mb-2">A+コンテンツ</h3>
                <div className="space-y-4">
                  {generatedContent.aPlusContent.map((module, index) => (
                    <div key={index} className="p-4 border border-gray-200 rounded-lg">
                      <h4 className="font-bold text-slate-700 mb-2">{module.moduleName}</h4>
                      <p className="text-sm text-gray-600 mb-1"><strong>目的:</strong> {module.purpose}</p>
                      <p className="text-sm text-gray-600 mb-1"><strong>大見出し:</strong> {module.bigHeadline}</p>
                      <p className="text-sm text-gray-600 mb-1"><strong>見出し:</strong> {module.headline}</p>
                      <p className="text-sm text-gray-600 mb-1"><strong>説明:</strong></p>
                      <div className="p-2 bg-gray-50 rounded text-sm whitespace-pre-wrap">{module.description}</div>
                      <p className="text-sm text-gray-600 mt-2"><strong>画像案:</strong> {module.imageSuggestion}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};
